---

- hosts: all
  vars:
    ppa: 'ppa:neovim-ppa/unstable'

  tasks:
    - apt_repository: repo="{{ ppa }}" state=present
      become: yes

    - apt: name=neovim state=latest
      become: yes

    - alternatives: name={{ item }} path=/usr/bin/nvim
      become: yes
      with_items:
        - vi
        - vim
        - editor

    - pip:
        name: neovim
        executable: "{{ item }}"
        state: present
        extra_args: --user
      with_items:
        - pip3
        - pip2

    - file:
        name: '~/.config/nvim'
        state: directory
        mode: 0755
    
    - copy:
        src: .vimrc
        dest: '~/.config/nvim/init.vim'
        mode: 0644

    - file: name='~/.local/share/nvim/site/autoload/' state=directory mode=0755

    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '~/.local/share/nvim/site/autoload/plug.vim'
        force: yes

    - command: nvim "+silent! PlugInstall" +qall!


    - name: 'For python jedi'
        pip:
          name: jedi
          executable: "{{ item }}"
          state: present
          extra_args: --user
        with_items:
          - pip3
          - pip2

    - name: 'Autopep'
        pip:
          name: autopep8
          executable: "{{ item }}"
          state: present
          extra_args: --user
        with_items:
          - pip3
          - pip2