---

- hosts: all
  vars:
    ppa: 'ppa:jonathonf/vim'

  tasks:
    - apt_repository: repo="{{ ppa }}" state=present
      become: yes

    - apt: name=vim state=latest
      become: yes

#    - alternatives: name={{ item }} path=/usr/bin/nvim
#      become: yes
#      with_items:
#        - vi
#        - vim
#        - editor

      #    - pip:
      #        name: neovim
      #        executable: "{{ item }}"
      #        state: present
      #        extra_args: --user
      #      with_items:
      #        - pip3
      #        - pip2

    - file:
        name: '~/.config/nvim'
        state: directory
        mode: 0755
    
    - copy:
        src: .vimrc
        dest: '~/.vimrc'
        mode: 0644

    - file: name='~/.vim/autoload/' state=directory mode=0755

    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '~/.vim/autoload/plug.vim'
        force: yes

    - command: vim "+silent! PlugInstall" +qall!


    - pip:
        name: jedi
        executable: "{{ item }}"
        state: present
        extra_args: --user
      with_items:
        - pip3
        - pip2

    - pip:
        name: autopep8
        executable: "{{ item }}"
        state: present
        extra_args: --user
      with_items:
        - pip3
        - pip2
