---

- hosts: all

  tasks:
    - package: name={{ item }} state=latest
      become: yes
      with_items:
        - tmux
        - mc
        - ack-grep
        - git
        - ansible
        - silversearcher-ag
